const LEGACY_MARY_KEY='mary-first-90-days-production';
const MARY_WORKSPACE_ID='9dc23f8e-8b42-4a75-b7d2-91b3f1df46ad';
const requestedWorkspaceId=new URLSearchParams(window.location.search).get('workspace')?.trim();
const ACTIVE_WORKSPACE_ID=requestedWorkspaceId||MARY_WORKSPACE_ID;
// Keep Mary's existing browser cache intact while giving future Journeys an
// isolated cache key.
const KEY=ACTIVE_WORKSPACE_ID===MARY_WORKSPACE_ID
  ? LEGACY_MARY_KEY
  : `journey-${ACTIVE_WORKSPACE_ID}`;
const SCHEMA_VERSION=4;
const START=new Date('2026-08-11T00:00:00');
const purposes=['Introduction','Business context','Workflow understanding','Tool walkthrough','KPI review','Process mapping','AI opportunity discovery','Roadmap alignment','Follow-up'];
const meetingWeeks=['Week 1','Week 2','Week 3','Week 4','Week 5 · Barcelona (F2F)'];
const makeActions=(items)=>items.map(text=>({text,done:false}));
const defaults={activeTab:'overview',activeWeek:0,weeklyAgenda:'',maryReflection30:'',yulaAssessment30:'',maryReflection60:'',yulaAssessment60:'',maryReflection90:'',yulaAssessment90:'',roadmapNow:'',roadmapNext:'',roadmapLater:'',manualTasks:{},weeks:[
{phase:'30',title:'Week 1 · Foundation and enablement',dates:'Aug 11–17',start:'2026-08-11',end:'2026-08-17',focus:'Become operational, understand the organizational landscape, and prepare the stakeholder and learning plan.',outcomes:['All required access requests submitted and tracked','Basic understanding of the studio, portfolio, business units and leadership structure','Stakeholder meetings from Week 2 onward scheduled','Weekly meetings established with Yula and Shronger'],actions:makeActions(['Secure access to ChatGPT Enterprise and Claude','Secure access to Jira, Confluence, GitHub, Slack and shared drives','Secure access to Looker and relevant business systems','Identify the relevant dashboards and internal systems for the first games','Review the studio structure, portfolio, business units and leadership structure','Schedule stakeholder introductions beginning in Week 2','Set a weekly 1:1 with Yula','Set a weekly sync with Shronger, Director Gen AI']),notes:'',marySatisfaction:0,yulaSatisfaction:0,reflection:''},
{phase:'30',title:'Week 2 · Initial immersion and guided exploration',dates:'Aug 18–24',start:'2026-08-18',end:'2026-08-24',focus:'Start meeting selected stakeholders, learn how the first game teams operate, and explore available tools and dashboards.',outcomes:['Initial stakeholder conversations completed','First game-team routines and decision flows observed','Core dashboards and business systems explored','Initial questions and learning gaps documented'],actions:makeActions(['Join selected game-team daily or recurring syncs as an observer','Meet the first prioritized stakeholders in the People tracker','Explore Looker dashboards for the first games','Review the main operational and business systems used by those games','Learn the basic business metrics used by each relevant function','Document unclear processes, terminology and areas requiring follow-up']),notes:'',marySatisfaction:0,yulaSatisfaction:0,reflection:''},
{phase:'30',title:'Week 3 · Broader immersion and Barcelona preparation',dates:'Aug 25–31',start:'2026-08-25',end:'2026-08-31',focus:'Broaden learning across teams, continue stakeholder meetings, and begin preparing the Barcelona agenda with Yula.',outcomes:['Broader exposure to game and functional routines','A clearer map of tools, dashboards and business measures','Barcelona objectives and priority meetings drafted','Early exploration themes documented without premature prioritization'],actions:makeActions(['Continue selected game-team dailies and functional syncs','Continue prioritized stakeholder introductions','Map which tools and dashboards are used by each team or game','Document basic business metrics relevant to Product, Analytics, Economy, Production, Community and VIP','Draft the Barcelona agenda and priority meeting list with Yula','Prepare context and questions for Barcelona introductions']),notes:'',marySatisfaction:0,yulaSatisfaction:0,reflection:''},
{phase:'30',title:'Week 4 · Local discovery and final Barcelona preparation',dates:'Sep 1–5',start:'2026-09-01',end:'2026-09-05',focus:'Continue local discovery and finalize the Barcelona schedule, objectives and preparation.',outcomes:['Barcelona agenda and meeting schedule confirmed','Clear objective and preparation for each F2F meeting','Continued understanding of workflows and business context','Open questions consolidated before the onsite visit'],actions:makeActions(['Continue selected stakeholder meetings and game-team routines','Finalize Barcelona people, schedule and meeting objectives with Yula','Prepare background, questions and expected outcomes for each Barcelona meeting','Review outstanding access, dashboard and business-context gaps','Capture the first themes related to manual effort, human error and capacity constraints']),notes:'',marySatisfaction:0,yulaSatisfaction:0,reflection:''},
{phase:'30',title:'Week 5 · Barcelona (F2F)',dates:'Sep 6–9',start:'2026-09-06',end:'2026-09-09',focus:'Use the Barcelona visit for high-value face-to-face introductions, context gathering and first-month synthesis.',outcomes:['Priority F2F introductions completed','Key takeaways and follow-ups captured','First-month organizational and workflow understanding summarized','Initial AI opportunity backlog ready for validation'],actions:makeActions(['Complete the Barcelona F2F meeting agenda','Capture key takeaways and actions after each meeting','Follow up on introductions and open questions from the visit','Summarize the organization, workflows, tools, dashboards and business metrics learned','Map initial high-manual-effort processes','Map initial human-error and capacity-gap themes','Create the initial structured AI opportunity backlog']),notes:'',marySatisfaction:0,yulaSatisfaction:0,reflection:''},
{phase:'60',title:'Week 6 · Portfolio mapping approach',dates:'Sep 10–16',start:'2026-09-10',end:'2026-09-16',focus:'Turn first-month learning into a consistent portfolio discovery and mapping method.',outcomes:['A repeatable mapping approach is drafted','Priority stakeholders for recurring routines are confirmed'],actions:makeActions(['Define a consistent method to map tool usage and workflow maturity across the portfolio','Establish recurring routines with the most relevant stakeholders']),notes:'',marySatisfaction:0,yulaSatisfaction:0,reflection:''},
{phase:'60',title:'Week 7 · Workflow opportunity mapping',dates:'Sep 17–23',start:'2026-09-17',end:'2026-09-23',focus:'Map the strongest operational themes where AI and automation could create value.',outcomes:['Manual effort, human-error exposure and capacity gaps are documented'],actions:makeActions(['Map manual, time-consuming work that could be automated','Map processes with high human-error exposure or repeated rework','Map capacity gaps where automation could support teams']),notes:'',marySatisfaction:0,yulaSatisfaction:0,reflection:''},
{phase:'60',title:'Week 8 · Backlog validation',dates:'Sep 24–30',start:'2026-09-24',end:'2026-09-30',focus:'Validate opportunity hypotheses and prioritize the backlog with stakeholders.',outcomes:['Opportunity backlog is validated and prioritized'],actions:makeActions(['Validate opportunity hypotheses with relevant stakeholders','Prioritize the opportunity backlog by impact, effort and readiness']),notes:'',marySatisfaction:0,yulaSatisfaction:0,reflection:''},
{phase:'60',title:'Week 9 · First solution definition',dates:'Oct 1–9',start:'2026-10-01',end:'2026-10-09',focus:'Select and scope the first small-to-medium optimization.',outcomes:['First optimization is selected, scoped and ready for delivery'],actions:makeActions(['Select the first small-to-medium optimization','Define scope, owner, dependencies and measurable success criteria','Create the initial delivery and adoption plan']),notes:'',marySatisfaction:0,yulaSatisfaction:0,reflection:''},
{phase:'90',title:'Week 10 · Build and launch',dates:'Oct 10–16',start:'2026-10-10',end:'2026-10-16',focus:'Move the first optimization or pilot into delivery.',outcomes:['First practical solution or pilot is launched'],actions:makeActions(['Build and launch the first practical AI optimization or validated pilot']),notes:'',marySatisfaction:0,yulaSatisfaction:0,reflection:''},
{phase:'90',title:'Week 11 · Measure and learn',dates:'Oct 17–23',start:'2026-10-17',end:'2026-10-23',focus:'Measure initial value, feedback and adoption.',outcomes:['Initial impact and lessons learned are documented'],actions:makeActions(['Measure initial business value, user feedback and adoption','Document lessons learned and adjust the delivery approach']),notes:'',marySatisfaction:0,yulaSatisfaction:0,reflection:''},
{phase:'90',title:'Week 12 · Prioritize the next six months',dates:'Oct 24–30',start:'2026-10-24',end:'2026-10-30',focus:'Turn discovery into a credible six-month backlog.',outcomes:['Six-month backlog is complete and prioritized'],actions:makeActions(['Complete and prioritize the six-month backlog','Align priority assumptions with relevant leaders']),notes:'',marySatisfaction:0,yulaSatisfaction:0,reflection:''},
{phase:'90',title:'Week 13 · Roadmap and operating model',dates:'Oct 31–Nov 8',start:'2026-10-31',end:'2026-11-08',focus:'Define the roadmap and repeatable working model for continued AI transformation.',outcomes:['High-level roadmap and operating model are aligned'],actions:makeActions(['Build and align a high-level roadmap covering delivery and organizational adoption','Define a repeatable intake, prioritization, delivery and knowledge-sharing process']),notes:'',marySatisfaction:0,yulaSatisfaction:0,reflection:''}
],
deliverables30:['Access and tool-readiness tracker','Organizational, portfolio and leadership overview','Stakeholder map and meeting plan','Initial map of dashboards, systems and business metrics','First structured AI opportunity backlog','Barcelona agenda, key takeaways and follow-up actions'],
success30:['Mary has all critical access required to work effectively','Mary understands the studio structure, portfolio and core business units at a practical level','Mary has begun building relationships with priority stakeholders','Mary understands the basic metrics, dashboards and systems used by the first game teams','An initial opportunity backlog and discovery baseline exist'].map(text=>({text,mary:false,yula:false})),
deliverables60:['Portfolio-level tool-usage and AI-maturity mapping approach','Established stakeholder routines and working cadence','Validated opportunity backlog','Impact-versus-effort prioritization','Defined first solution scope, dependencies and success measures','Initial delivery and adoption plan'],
success60:['A repeatable portfolio discovery and mapping approach is in use','Recurring routines exist with the right stakeholders','The highest-value manual effort, human-error and capacity-gap themes are documented','The opportunity backlog is validated and prioritized','The first optimization is selected, scoped and ready for delivery'].map(text=>({text,mary:false,yula:false})),
deliverables90:['First delivered AI optimization or validated pilot','Impact, feedback and lessons-learned summary','Prioritized six-month backlog','High-level roadmap for solutions, adoption and culture','Draft operating model for future AI initiatives','Knowledge-sharing and enablement cadence'],
success90:['A practical AI optimization or validated pilot has been delivered','Initial value, feedback and adoption have been measured','The six-month backlog is prioritized and credible','The high-level roadmap is aligned with relevant leaders','A repeatable working model for continued AI transformation is defined'].map(text=>({text,mary:false,yula:false})),
people:[{"name":"Shrungar Dadarkar","role":"Director, Generative AI","studio":"Central","priority":"Critical","meetingWeek":"Week 2","purpose":"Roadmap alignment","status":"Not scheduled","followUp":"Weekly","takeaways":""},{"name":"Akshay Krishna Dhumal","role":"GenAI Project Manager","studio":"Central","priority":"High","meetingWeek":"Week 2","purpose":"Introduction","status":"Not scheduled","followUp":"No","takeaways":""},{"name":"Ketan Velip","role":"Lead Engineer","studio":"Central","priority":"High","meetingWeek":"Week 2","purpose":"Workflow understanding","status":"Not scheduled","followUp":"No","takeaways":""},{"name":"Giancarlo Lucchese","role":"Director, QA Automation Engineering","studio":"Central","priority":"Medium","meetingWeek":"Week 3","purpose":"AI opportunity discovery","status":"Not scheduled","followUp":"No","takeaways":""},{"name":"Gabriele Simonetti","role":"Senior Manager of AI Solutions","studio":"Central","priority":"Medium","meetingWeek":"Week 2","purpose":"Introduction","status":"Not scheduled","followUp":"No","takeaways":""},{"name":"Caso Santiago","role":"AI Architect","studio":"MGO","priority":"Medium","meetingWeek":"Week 3","purpose":"Workflow understanding","status":"Not scheduled","followUp":"No","takeaways":""},{"name":"Alberto Fernandez Martinez","role":"VP, Live Technology","studio":"MGO","priority":"Low","meetingWeek":"Week 3","purpose":"Business context","status":"Not scheduled","followUp":"No","takeaways":""},{"name":"Sricharan Prasad","role":"Senior Manager Production","studio":"Bingo Bash","priority":"Medium","meetingWeek":"Week 3","purpose":"Workflow understanding","status":"Not scheduled","followUp":"No","takeaways":""},{"name":"Sandeep Sekhar","role":"Sr. Director, Art","studio":"Bingo Bash","priority":"Medium","meetingWeek":"Week 3","purpose":"Workflow understanding","status":"Not scheduled","followUp":"No","takeaways":""},{"name":"Chris Berghauser","role":"Senior Director of Community & Player Experience","studio":"Central","priority":"Medium","meetingWeek":"Week 3","purpose":"Business context","status":"Not scheduled","followUp":"No","takeaways":""},{"name":"Kristina Hamilton","role":"VP, Marketing Operations","studio":"Central","priority":"Medium","meetingWeek":"Week 3","purpose":"Business context","status":"Not scheduled","followUp":"No","takeaways":""},{"name":"Steve Huff","role":"President, Games","studio":"Central","priority":"Medium","meetingWeek":"Week 5 \u00b7 Barcelona (F2F)","purpose":"Introduction","status":"Not scheduled","followUp":"No","takeaways":""},{"name":"Samuel Amzallag","role":"Associate Lead Producer","studio":"Stumble Guys","priority":"Medium","meetingWeek":"Week 5 \u00b7 Barcelona (F2F)","purpose":"Workflow understanding","status":"Not scheduled","followUp":"No","takeaways":""}],initiatives:[],resources:[]};
let state=structuredClone(defaults);let readOnlyMode=false;const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function merge(base,saved){if(Array.isArray(base))return Array.isArray(saved)?saved:base;if(base&&typeof base==='object'){const r={...base};Object.keys(saved||{}).forEach(k=>r[k]=k in base?merge(base[k],saved[k]):saved[k]);return r}return saved===undefined?base:saved}
function validWorkspace(v){return v&&typeof v==='object'&&(Array.isArray(v.people)||Array.isArray(v.weeks)||Array.isArray(v.initiatives))}
function candidateScore(v){if(!validWorkspace(v))return -1;const p=(v.people||[]).filter(x=>x&&String(x.name||'').trim()).length;const i=(v.initiatives||[]).filter(x=>x&&String(x.title||'').trim()).length;const c=(v.weeks||[]).flatMap(w=>w.actions||[]).filter(a=>a.done).length;return p*1000+i*100+c}
function migrateLegacy(){if(ACTIVE_WORKSPACE_ID!==MARY_WORKSPACE_ID)return null;let best=null,bestKey='',score=-1;for(let n=0;n<localStorage.length;n++){const k=localStorage.key(n);if(!k||k===KEY||!/(mary|aiTransformation)/i.test(k))continue;try{const v=JSON.parse(localStorage.getItem(k));const s=candidateScore(v);if(s>score){best=v;bestKey=k;score=s}}catch(e){}}if(!best)return null;const migrated=merge(structuredClone(defaults),best);migrated.schemaVersion=SCHEMA_VERSION;migrated.migratedFrom=bestKey;localStorage.setItem(KEY,JSON.stringify(migrated));return migrated}
try{
  const existing=localStorage.getItem(KEY);
  state=existing?merge(structuredClone(defaults),JSON.parse(existing)):(migrateLegacy()||structuredClone(defaults));
  const currentPeople=(state.people||[]).filter(x=>x&&String(x.name||'').trim()).length;
  if(currentPeople===0){
    const recovered=migrateLegacy();
    if(recovered&&candidateScore(recovered)>candidateScore(state))state=recovered;
    else if((defaults.people||[]).length)state.people=structuredClone(defaults.people);
  }
}catch(e){state=structuredClone(defaults)}
state.schemaVersion=SCHEMA_VERSION;
let cloudNotificationsEnabled=true;
function save(options={}){
  if(readOnlyMode && options.force!==true)return;
  state.schemaVersion=SCHEMA_VERSION;
  state.updatedAt=new Date().toISOString();
  localStorage.setItem(KEY,JSON.stringify(state));
  localStorage.setItem(KEY+'-backup',JSON.stringify(state));
  const status=$('#saveStatus');
  if(status)status.textContent=options.statusText||'Saved locally';
  if(cloudNotificationsEnabled&&options.notifyCloud!==false){
    window.dispatchEvent(new CustomEvent('workspace-local-changed',{detail:{state:structuredClone(state)}}));
  }
}
function getWorkspaceState(){return structuredClone(state)}
function applyWorkspaceState(nextState,options={}){
  if(!validWorkspace(nextState))throw new Error('Invalid workspace state');
  const localActiveTab=state.activeTab;
  const localActiveWeek=state.activeWeek;
  cloudNotificationsEnabled=false;
  try{
    state=merge(structuredClone(defaults),nextState);
    state.activeTab=localActiveTab||state.activeTab||'overview';
    state.activeWeek=Number.isInteger(localActiveWeek)?localActiveWeek:(state.activeWeek||0);
    state.schemaVersion=SCHEMA_VERSION;
    if(options.persistLocal!==false)save({notifyCloud:false,statusText:options.statusText||'Loaded from cloud'});
    render();
  }finally{
    cloudNotificationsEnabled=true;
  }
}
function setReadOnly(value){readOnlyMode=Boolean(value);document.body.classList.toggle('read-only-mode',readOnlyMode);}
window.workspaceApp={getState:getWorkspaceState,applyState:applyWorkspaceState,saveLocal:()=>save({notifyCloud:false,force:true}),setReadOnly,isReadOnly:()=>readOnlyMode};
function today(){const t=new Date();t.setHours(0,0,0,0);return t}
function dateOnly(s){return new Date(s+'T00:00:00')}
function currentWeekIndex(){
  const t=today();
  const schedule=state.weeks;
  if(t<dateOnly(schedule[0].start))return 0;
  for(let i=0;i<schedule.length;i++){
    if(t>=dateOnly(schedule[i].start)&&t<=dateOnly(schedule[i].end))return i;
  }
  return schedule.length-1;
}
function phase(){const i=currentWeekIndex();return state.weeks[i].phase==='30'?'30 Days':state.weeks[i].phase==='60'?'60 Days':'90 Days'}
function nav(){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.activeTab));$$('.panel').forEach(p=>p.classList.toggle('active',p.id===state.activeTab))}
$$('.tab').forEach(b=>b.onclick=()=>{state.activeTab=b.dataset.tab;nav();localStorage.setItem(KEY,JSON.stringify(state))});$$('.week-tab').forEach(b=>b.onclick=()=>{state.activeWeek=+b.dataset.week;renderWeek();localStorage.setItem(KEY,JSON.stringify(state))});
function bindFields(){$$('[data-field]').forEach(f=>{const k=f.dataset.field;f.value=state[k]||'';f.oninput=e=>{state[k]=e.target.value;save()}})}
function manualFor(i){state.manualTasks[i]=state.manualTasks[i]||[];return state.manualTasks[i]}
function overviewItems(){const w=currentWeekIndex(),items=[];for(let i=0;i<w;i++)state.weeks[i].actions.forEach((a,j)=>{if(!a.done)items.push({kind:'week',w:i,j,item:a,carry:true})});state.weeks[w].actions.forEach((a,j)=>items.push({kind:'week',w,j,item:a,carry:false}));manualFor(w).forEach((a,j)=>items.push({kind:'manual',w,j,item:a,carry:false}));return items}
function escapeAttr(v){return String(v||'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;')}
function renderOverview(){const w=currentWeekIndex();$('#overviewWeekTitle').textContent=state.weeks[w].title;$('#currentWeekLabel').textContent=`Week ${w+1}`;const root=$('#overviewTasks');root.innerHTML='';overviewItems().forEach(x=>{const d=document.createElement('div');d.className='task-card';d.innerHTML=`<input type="checkbox" ${x.item.done?'checked':''}><input value="${escapeAttr(x.item.text)}"><button>×</button>`;const[cb,inp,del]=d.children;cb.onchange=e=>{x.item.done=e.target.checked;renderOverview();progress();save()};inp.oninput=e=>{x.item.text=e.target.value;save()};del.onclick=()=>{if(x.kind==='manual')manualFor(x.w).splice(x.j,1);else state.weeks[x.w].actions.splice(x.j,1);renderOverview();progress();save()};root.appendChild(d)});progress()}
$('#addManualTask').onclick=()=>{const w=currentWeekIndex();manualFor(w).push({text:'',done:false});renderOverview();save()}
function rating(label,val,key){return `<div><label>${label}</label><div class="rating">${[1,2,3,4,5].map(n=>`<button data-rate="${key}" data-value="${n}" class="${val===n?'active':''}">${n}</button>`).join('')}</div></div>`}
function renderWeek(){const w=state.weeks[state.activeWeek];$$('.week-tab').forEach(b=>b.classList.toggle('active',+b.dataset.week===state.activeWeek));const carry=[];const started=today()>=dateOnly(w.start);if(started){for(let i=0;i<state.activeWeek;i++)state.weeks[i].actions.forEach((a,j)=>{if(!a.done)carry.push({i,j,a})})}const root=$('#weekDetail');root.innerHTML=`<div class="week-layout"><article class="week-summary"><p class="eyebrow">${w.dates}${state.activeWeek===4?'<span class="week-special">F2F</span>':''}</p><h2>${w.title}</h2><p>${w.focus}</p><div class="section-label">Expected outcomes</div><ul class="standard-list">${w.outcomes.map(x=>`<li>${x}</li>`).join('')}</ul><div class="section-label">Week notes</div><textarea id="weekNotes">${w.notes||''}</textarea></article><article class="week-actions">${carry.length?`<div class="carryover"><strong>Outstanding tasks from previous weeks</strong>${carry.map(c=>`<label class="task-row"><input type="checkbox" data-carry="${c.i}:${c.j}"><span><small class="source-week">Week ${c.i+1}</small>${c.a.text}</span></label>`).join('')}</div>`:''}<p class="eyebrow">Key activities</p>${w.actions.map((a,i)=>`<label class="task-row"><input type="checkbox" data-action="${i}" ${a.done?'checked':''}><span>${a.text}</span></label>`).join('')}</article></div><div class="week-reflection">${rating("Mary's satisfaction",w.marySatisfaction,'mary')}${rating("Yula's assessment",w.yulaSatisfaction,'yula')}<div><label>How did the week go?</label><textarea id="weekReflection">${w.reflection||''}</textarea></div></div>`;$('#weekNotes').oninput=e=>{w.notes=e.target.value;save()};$('#weekReflection').oninput=e=>{w.reflection=e.target.value;save()};root.querySelectorAll('[data-action]').forEach(c=>c.onchange=e=>{w.actions[+e.target.dataset.action].done=e.target.checked;renderOverview();progress();save()});root.querySelectorAll('[data-carry]').forEach(c=>c.onchange=e=>{const[i,j]=e.target.dataset.carry.split(':').map(Number);state.weeks[i].actions[j].done=e.target.checked;renderWeek();renderOverview();progress();save()});root.querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>{if(b.dataset.rate==='mary')w.marySatisfaction=+b.dataset.value;else w.yulaSatisfaction=+b.dataset.value;renderWeek();save()})}
function list(sel,arr){$(sel).innerHTML=arr.map(x=>`<li>${x}</li>`).join('')}
function phaseWeeks(code){return state.weeks.map((w,i)=>({w,i})).filter(x=>x.w.phase===code)}
function renderPhaseObjectives(sel,code){const r=$(sel);r.innerHTML='';phaseWeeks(code).forEach(({w,i})=>{const group=document.createElement('div');group.className='phase-task-group';group.innerHTML=`<h4>${w.title}</h4><p>${w.dates}</p>`;w.actions.forEach((a,j)=>{const l=document.createElement('label');l.className='task-row';l.innerHTML=`<input type="checkbox" ${a.done?'checked':''}><span>${a.text}</span>`;l.querySelector('input').onchange=e=>{state.weeks[i].actions[j].done=e.target.checked;renderOverview();progress();save()};group.appendChild(l)});r.appendChild(group)})}
function success(sel,key){const r=$(sel);r.innerHTML='';state[key].forEach(x=>{const d=document.createElement('div');d.className='success-row';d.innerHTML=`<span>${x.text}</span><label>Mary <input type="checkbox" data-who="mary" ${x.mary?'checked':''}></label><label>Yula <input type="checkbox" data-who="yula" ${x.yula?'checked':''}></label>`;d.querySelectorAll('input').forEach(c=>c.onchange=e=>{x[e.target.dataset.who]=e.target.checked;save()});r.appendChild(d)})}
function inp(v,fn,type='text'){const td=document.createElement('td'),i=document.createElement('input');i.type=type;i.value=v||'';i.oninput=e=>{fn(e.target.value);save()};td.appendChild(i);return td}
function sel(v,opts,fn){const td=document.createElement('td'),s=document.createElement('select');opts.forEach(o=>{const p=document.createElement('option');p.value=o;p.textContent=o;p.selected=o===v;s.appendChild(p)});s.onchange=e=>{fn(e.target.value);save()};td.appendChild(s);return td}
function area(v,fn){const td=document.createElement('td'),a=document.createElement('textarea');a.value=v||'';a.oninput=e=>{fn(e.target.value);save()};td.appendChild(a);return td}
function del(coll,i,render){
  const td=document.createElement('td'),b=document.createElement('button');
  b.className='icon';
  b.textContent='×';
  b.onclick=()=>{state[coll].splice(i,1);render();save()};
  td.appendChild(b);
  return td;
}
function people(){const b=$('#peopleBody');b.innerHTML='';state.people.forEach((p,i)=>{const tr=document.createElement('tr');tr.append(inp(p.name,v=>p.name=v),inp(p.role,v=>p.role=v),inp(p.studio,v=>p.studio=v),sel(p.priority,['Critical','High','Medium','Low'],v=>p.priority=v),sel(p.meetingWeek||'Week 2',meetingWeeks,v=>p.meetingWeek=v),sel(p.purpose,purposes,v=>p.purpose=v),sel(p.status,['Not scheduled','Scheduled','Completed','Recurring'],v=>p.status=v),sel(p.followUp,['No','Recommended','Required','Completed','Weekly','Monthly'],v=>p.followUp=v),area(p.takeaways,v=>p.takeaways=v),del('people',i,people));b.appendChild(tr)})}
function initiatives(){const b=$('#initiativesBody');b.innerHTML='';state.initiatives.forEach((x,i)=>{const tr=document.createElement('tr');tr.append(inp(x.title,v=>x.title=v),inp(x.team,v=>x.team=v),sel(x.problemType,['Manual effort','Human error','Capacity gap','Knowledge access','Other'],v=>x.problemType=v),sel(x.estimatedTime,['< 1 week','1–2 weeks','3–4 weeks','1–2 months','3+ months'],v=>x.estimatedTime=v),sel(x.scope,['Single workflow','Single team','Multiple teams','Studio-wide','Portfolio-wide'],v=>x.scope=v),sel(x.type,['Quick Win','Project'],v=>x.type=v),sel(x.impact,['Low','Medium','High'],v=>x.impact=v),sel(x.priority,['Low','Medium','High'],v=>x.priority=v),sel(x.status,['Idea','Discovery','Prioritized','In Progress','Delivered'],v=>x.status=v),area(x.notes,v=>x.notes=v),del('initiatives',i,initiatives));b.appendChild(tr)})}
function resources(){const b=$('#resourcesBody');b.innerHTML='';state.resources.forEach((x,i)=>{const tr=document.createElement('tr');const open=document.createElement('td'),a=document.createElement('a');a.className='resource-open'+(x.link?'':' disabled');a.textContent='Open';a.target='_blank';a.rel='noopener noreferrer';a.href=x.link||'#';open.appendChild(a);tr.append(inp(x.name,v=>x.name=v),area(x.description,v=>x.description=v),inp(x.link,v=>{x.link=v;resources()}),open,del('resources',i,resources));b.appendChild(tr)})}
$('#addPerson').onclick=()=>{state.people.push({name:'',role:'',studio:'',priority:'Medium',meetingWeek:'Week 2',purpose:'Introduction',status:'Not scheduled',followUp:'No',takeaways:''});people();save()};$('#addInitiative').onclick=()=>{state.initiatives.push({title:'',team:'',problemType:'Manual effort',estimatedTime:'1–2 weeks',scope:'Single workflow',type:'Quick Win',impact:'Medium',priority:'Medium',status:'Idea',notes:''});initiatives();save()};$('#addResource').onclick=()=>{state.resources.push({name:'',description:'',link:''});resources();save()}
function ratio(done,total){return total?Math.round(done/total*100):0}
function phaseProgress(code){const indexes=phaseWeeks(code).map(x=>x.i),tasks=indexes.flatMap(i=>[...state.weeks[i].actions,...manualFor(i)]),done=tasks.filter(x=>x.done).length;return{done,total:tasks.length,p:ratio(done,tasks.length)}}
function progress(){const items=overviewItems(),done=items.filter(x=>x.item.done).length,total=items.length,p=ratio(done,total);$('#weeklyProgressValue').textContent=`${p}%`;$('#weeklyProgressCount').textContent=`${done} / ${total}`;$('#weeklyProgressBar').style.width=`${p}%`;$('#weekStatus').textContent=p>=70?'On Track':'Needs Attention';$('#weekStatus').style.color=p>=70?'#14805e':'#b76d13';for(const [code,prefix] of [['30','30'],['60','60'],['90','90']]){const v=phaseProgress(code);$(`#progress${prefix}Value`).textContent=`${v.p}%`;$(`#progress${prefix}Count`).textContent=`${v.done} / ${v.total}`}$('#currentPhase').textContent=phase()}
function render(){nav();renderOverview();renderWeek();list('#deliverables30',state.deliverables30);success('#success30','success30');renderPhaseObjectives('#objectives60','60');list('#deliverables60',state.deliverables60);success('#success60','success60');renderPhaseObjectives('#objectives90','90');list('#deliverables90',state.deliverables90);success('#success90','success90');people();initiatives();resources();bindFields();progress()}
render();
