import { initializeApp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import { browserLocalPersistence, getAuth, GoogleAuthProvider, onAuthStateChanged, setPersistence, signInWithPopup } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import { addDoc, collection, doc, getDoc, getFirestore, serverTimestamp, updateDoc } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import { firebaseConfig, hubAdminEmail } from "./firebase-config.js";

const params = new URLSearchParams(location.search);
const templateId = params.get("template");
const draftId = params.get("draft");
const app = initializeApp(firebaseConfig, "lgp-assign-journey");
const auth = getAuth(app);
const db = getFirestore(app);
const $ = selector => document.querySelector(selector);
let template, currentUser, draft;

function message(text, error = false) { $("#status").textContent = text; $("#status").classList.toggle("error", error); }
function values() { const form = new FormData($("#assignForm")); return { employeeName: String(form.get("employeeName") || "").trim(), employeeEmail: String(form.get("employeeEmail") || "").trim().toLowerCase(), managerName: String(form.get("managerName") || "").trim(), managerEmail: String(form.get("managerEmail") || "").trim().toLowerCase(), startDate: String(form.get("startDate") || "") }; }
function fill(data) { Object.entries(data).forEach(([key, value]) => { const input = document.querySelector(`[name="${key}"]`); if (input) input.value = value || ""; }); }
function setBusy(value) { $("#saveDraft").disabled = value; $("#submit").disabled = value; }
function validForSubmission(data) { return data.employeeName && data.employeeEmail && data.managerName && data.managerEmail && data.startDate; }
function dateRange(start, index) { const from = new Date(`${start}T00:00:00`); from.setDate(from.getDate() + index * 7); const to = new Date(from); to.setDate(to.getDate() + 6); const date = value => value.toISOString().slice(0, 10); return { start: date(from), end: date(to), dates: `${new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" }).format(from)} – ${new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" }).format(to)}` }; }
function phase(index) { return index < 5 ? "30" : index < 9 ? "60" : "90"; }
function createWorkspaceData(startDate) { const weeks = template.weeks.map((week, index) => ({ phase: phase(index), title: `Week ${index + 1} · ${week.title}`, ...dateRange(startDate, index), focus: week.focus, outcomes: Array.isArray(week.outcomes) && week.outcomes.length ? week.outcomes : [`Complete the planned ${week.title.toLowerCase()} activities and record key decisions.`], actions: (week.activities || []).map(text => ({ text, done: false })), notes: "", marySatisfaction: 0, yulaSatisfaction: 0, reflection: "" })); const phaseDeliverables = code => template.phaseDeliverables?.[code] || weeks.filter(week => week.phase === code).flatMap(week => week.actions.slice(0, 2).map(action => action.text)); const successFor = code => [{ text: template.phaseSuccessCriteria?.[code] || "Phase success criteria to be completed.", mary: false, yula: false }]; const initiatives = (template.initiativesOrLearningAreas || []).map(title => ({ title, team: "", problemType: "Other", estimatedTime: "1–2 weeks", scope: "Single workflow", type: "Project", impact: "Medium", priority: "Medium", status: "Idea", notes: "Suggested from the role template" })); const resources = (template.suggestedResources || []).map(name => ({ name, description: `Suggested ${template.templateName} resource`, link: "" })); return { schemaVersion: 4, activeTab: "overview", activeWeek: 0, weeklyAgenda: "", maryReflection30: "", yulaAssessment30: "", maryReflection60: "", yulaAssessment60: "", maryReflection90: "", yulaAssessment90: "", roadmapNow: "", roadmapNext: "", roadmapLater: "", manualTasks: {}, weeks, deliverables30: phaseDeliverables("30"), success30: successFor("30"), deliverables60: phaseDeliverables("60"), success60: successFor("60"), deliverables90: phaseDeliverables("90"), success90: successFor("90"), people: [], initiatives, resources }; }
function metadata(data, status) { return { employeeName: data.employeeName, employee: { name: data.employeeName, email: data.employeeEmail }, managerName: data.managerName, manager: { name: data.managerName, email: data.managerEmail }, roleTitle: template.templateName, template: template.templateName, templateId: template.templateId, templateVersion: template.templateVersion, startDate: data.startDate, status, draft: status === "Draft", ownerUid: currentUser.uid, ownerEmail: currentUser.email || "", createdBy: { uid: currentUser.uid, email: currentUser.email || "" }, roleMission: template.roleMission || "", roleMissionDescription: template.description }; }
async function loadTemplate() { if (!templateId) throw new Error("Choose a template from the Hub."); const response = await fetch(`templates/${encodeURIComponent(templateId)}.json`); if (!response.ok) throw new Error("This template is not available."); template = await response.json(); $("#templateName").textContent = template.templateName; $("#templateDescription").textContent = template.description; $("#back").href = `template.html?template=${encodeURIComponent(templateId)}`; if (draftId) { const snapshot = await getDoc(doc(db, "workspaces", draftId)); if (!snapshot.exists() || snapshot.data().ownerEmail?.toLowerCase() !== currentUser.email?.toLowerCase()) throw new Error("This draft is not available."); draft = snapshot.data(); fill({ employeeName: draft.employeeName, employeeEmail: draft.employee?.email, managerName: draft.managerName, managerEmail: draft.manager?.email, startDate: draft.startDate }); $("#mode").textContent = "Continue draft"; } }
async function saveDraft() { const data = values(); setBusy(true); message("Saving draft…"); try { const draftMetadata = { ...metadata(data, "Draft"), editors: [currentUser.email || ""].filter(Boolean), updatedAt: serverTimestamp() }; if (draftId) { await updateDoc(doc(db, "workspaces", draftId), draftMetadata); } else { const ref = await addDoc(collection(db, "workspaces"), { ...draftMetadata, createdAt: serverTimestamp() }); location.replace(`assign.html?template=${encodeURIComponent(templateId)}&draft=${encodeURIComponent(ref.id)}`); return; } message("Draft saved. You can return to the Hub and continue it later."); } catch (error) { console.error("Save draft failed", error); message(error?.message || "Draft could not be saved.", true); } finally { setBusy(false); } }
async function submit(event) { event.preventDefault(); const data = values(); if (!validForSubmission(data)) { message("Add employee and manager names, emails, and a start date before submitting.", true); return; } setBusy(true); message("Creating Production Journey…"); try { const production = { ...metadata(data, "Production"), editors: [...new Set([data.employeeEmail, data.managerEmail])], templateSnapshot: structuredClone(template), workspaceData: createWorkspaceData(data.startDate), updatedAt: serverTimestamp() }; let id = draftId; if (draftId) await updateDoc(doc(db, "workspaces", draftId), production); else { const ref = await addDoc(collection(db, "workspaces"), { ...production, createdAt: serverTimestamp() }); id = ref.id; } location.assign(`index.html?workspace=${encodeURIComponent(id)}`); } catch (error) { console.error("Create Journey failed", error); message(error?.code === "permission-denied" ? "Only the pilot Hub administrator can submit a Journey." : error?.message || "Journey creation failed.", true); setBusy(false); } }
$("#signIn").onclick = async () => { const provider = new GoogleAuthProvider(); provider.setCustomParameters({ hd: "scopely.com" }); await setPersistence(auth, browserLocalPersistence); await signInWithPopup(auth, provider); };
$("#saveDraft").onclick = saveDraft; $("#assignForm").addEventListener("submit", submit);
onAuthStateChanged(auth, async user => { if (!user || !user.email?.toLowerCase().endsWith("@scopely.com")) return; if (user.email.toLowerCase() !== hubAdminEmail.toLowerCase()) { $("#message").textContent = "Only the pilot Hub administrator can assign a Journey."; return; } currentUser = user; $("#gate").hidden = true; $("#app").hidden = false; try { await loadTemplate(); } catch (error) { message(error.message, true); } });
