import { initializeApp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import { browserLocalPersistence, getAuth, GoogleAuthProvider, onAuthStateChanged, setPersistence, signInWithPopup } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import { addDoc, collection, getFirestore, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import { firebaseConfig, hubAdminEmail } from "./firebase-config.js";

const templateId = new URLSearchParams(location.search).get("template");
const app = initializeApp(firebaseConfig, "lgp-assign-journey");
const auth = getAuth(app);
const db = getFirestore(app);
const $ = selector => document.querySelector(selector);
let template;
let currentUser;

function message(text, error = false) { $("#status").textContent = text; $("#status").classList.toggle("error", error); }
function dateRange(start, index) { const from = new Date(`${start}T00:00:00`); from.setDate(from.getDate() + index * 7); const to = new Date(from); to.setDate(to.getDate() + 6); const date = value => value.toISOString().slice(0, 10); return { start: date(from), end: date(to), dates: `${new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" }).format(from)} – ${new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" }).format(to)}` }; }
function phase(index) { return index < 5 ? "30" : index < 9 ? "60" : "90"; }
function outcomes(week) { return Array.isArray(week.outcomes) && week.outcomes.length ? week.outcomes : [`Complete the planned ${week.title.toLowerCase()} activities and record key decisions.`]; }
function createWorkspaceData(startDate) {
  const weeks = template.weeks.map((week, index) => ({ phase: phase(index), title: `Week ${index + 1} · ${week.title}`, ...dateRange(startDate, index), focus: week.focus, outcomes: outcomes(week), actions: (week.activities || []).map(text => ({ text, done: false })), notes: "", marySatisfaction: 0, yulaSatisfaction: 0, reflection: "" }));
  const activitiesFor = code => weeks.filter(week => week.phase === code).flatMap(week => week.actions.slice(0, 2).map(action => action.text));
  const successFor = code => activitiesFor(code).slice(0, 4).map(text => ({ text, mary: false, yula: false }));
  return { schemaVersion: 4, activeTab: "overview", activeWeek: 0, weeklyAgenda: "", maryReflection30: "", yulaAssessment30: "", maryReflection60: "", yulaAssessment60: "", maryReflection90: "", yulaAssessment90: "", roadmapNow: "", roadmapNext: "", roadmapLater: "", manualTasks: {}, weeks, deliverables30: activitiesFor("30"), success30: successFor("30"), deliverables60: activitiesFor("60"), success60: successFor("60"), deliverables90: activitiesFor("90"), success90: successFor("90"), people: [], initiatives: [], resources: [] };
}
async function loadTemplate() { if (!templateId) throw new Error("Choose a template from the Hub."); const response = await fetch(`templates/${encodeURIComponent(templateId)}.json`); if (!response.ok) throw new Error("This template is not available."); template = await response.json(); $("#templateName").textContent = template.templateName; $("#templateDescription").textContent = template.description; $("#back").href = `template.html?template=${encodeURIComponent(templateId)}`; }
$("#signIn").onclick = async () => { const provider = new GoogleAuthProvider(); provider.setCustomParameters({ hd: "scopely.com" }); await setPersistence(auth, browserLocalPersistence); await signInWithPopup(auth, provider); };
$("#assignForm").addEventListener("submit", async event => { event.preventDefault(); if (!template || !currentUser) return; const form = new FormData(event.currentTarget); const employee = { name: String(form.get("employeeName")).trim(), email: String(form.get("employeeEmail")).trim().toLowerCase() }; const manager = { name: String(form.get("managerName")).trim(), email: String(form.get("managerEmail")).trim().toLowerCase() }; const startDate = String(form.get("startDate")); const submit = $("#submit"); submit.disabled = true; message("Creating Journey…"); try { const ref = await addDoc(collection(db, "workspaces"), { employeeName: employee.name, employee, managerName: manager.name, manager, roleTitle: template.templateName, template: template.templateName, templateId: template.templateId, templateVersion: template.templateVersion, startDate, status: "Active", editors: [...new Set([employee.email, manager.email])], ownerUid: currentUser.uid, ownerEmail: currentUser.email || "", createdBy: { uid: currentUser.uid, email: currentUser.email || "" }, schemaVersion: 4, roleMission: template.roleMission || "", roleMissionDescription: template.description, createdAt: serverTimestamp(), updatedAt: serverTimestamp(), workspaceData: createWorkspaceData(startDate) }); location.assign(`index.html?workspace=${encodeURIComponent(ref.id)}`); } catch (error) { console.error("Create Journey failed", error); message(error?.code === "permission-denied" ? "Only the pilot Hub administrator can create Journeys." : error?.message || "Journey creation failed.", true); submit.disabled = false; } });
onAuthStateChanged(auth, async user => { if (!user || !user.email?.toLowerCase().endsWith("@scopely.com")) return; if (user.email.toLowerCase() !== hubAdminEmail.toLowerCase()) { $("#gate").hidden = true; $("#message").textContent = "Only the pilot Hub administrator can assign a Journey."; return; } currentUser = user; $("#gate").hidden = true; $("#app").hidden = false; try { await loadTemplate(); } catch (error) { message(error.message, true); } });
