import { initializeApp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import { browserLocalPersistence, getAuth, GoogleAuthProvider, onAuthStateChanged, setPersistence, signInWithPopup, signInWithRedirect, signOut } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import { collection, deleteDoc, doc, getDocs, getFirestore, orderBy, query } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import { firebaseConfig, hubAdminEmail } from "./firebase-config.js";

const roles = [
  { id: "ai-transformation-lead", name: "AI Transformation Lead", category: "Leadership & Transformation", status: "Ready", description: "AI strategy, delivery and enablement." },
  { id: "data-analyst", name: "Data Analyst", category: "Analytics", status: "Ready", description: "Analytics, insights and decision support." },
  { id: "data-scientist", name: "Data Scientist", category: "Analytics", status: "Coming Soon", description: "Advanced modeling and experimentation." },
  { id: "bi-analyst", name: "BI Analyst", category: "Analytics", status: "Coming Soon", description: "Reporting and business intelligence." },
  { id: "product-manager", name: "Product Manager", category: "Product", status: "Coming Soon", description: "Product strategy and execution." },
  { id: "producer", name: "Producer", category: "Product", status: "Coming Soon", description: "Delivery planning and coordination." },
  { id: "monetization-manager", name: "Monetization Manager", category: "Monetization & Economy", status: "Ready", description: "Pricing, offers, LiveOps and growth." },
  { id: "economy-manager", name: "Economy Manager", category: "Monetization & Economy", status: "Coming Soon", description: "Game economy strategy." },
  { id: "liveops-manager", name: "LiveOps Manager", category: "Live Operations", status: "Coming Soon", description: "Live events and player engagement." },
  { id: "crm-manager", name: "CRM Manager", category: "Marketing & Player Engagement", status: "Coming Soon", description: "Lifecycle and player communication." },
  { id: "user-acquisition-manager", name: "User Acquisition Manager", category: "Marketing & Player Engagement", status: "Coming Soon", description: "Growth and acquisition." },
  { id: "community-manager", name: "Community Manager", category: "Marketing & Player Engagement", status: "Coming Soon", description: "Community and player voice." },
  { id: "engineering-manager", name: "Engineering Manager", category: "Engineering & Quality", status: "Coming Soon", description: "Engineering leadership." },
  { id: "qa-manager", name: "QA Manager", category: "Engineering & Quality", status: "Coming Soon", description: "Quality strategy and delivery." }
];

// Do not restore an obsolete Hub from the browser back/forward cache.
window.addEventListener("unload", () => {});
window.addEventListener("pageshow", event => { if (event.persisted) window.location.reload(); });
const app = initializeApp(firebaseConfig), auth = getAuth(app), db = getFirestore(app), provider = new GoogleAuthProvider();
provider.setCustomParameters({ hd: "scopely.com" });
const $ = id => document.getElementById(id);
const els = { loginGate: $("loginGate"), hubShell: $("hubShell"), signInButton: $("signInButton"), signOutButton: $("signOutButton"), loginMessage: $("loginMessage"), userName: $("userName"), userEmail: $("userEmail"), userAvatar: $("userAvatar"), welcomeTitle: $("welcomeTitle"), journeyGrid: $("journeyGrid"), journeyState: $("journeyState"), journeyCount: $("journeyCount"), viewAllJourneys: $("viewAllJourneys"), roleSearch: $("roleSearch"), roleCount: $("roleCount"), roleLibraryGrid: $("roleLibraryGrid"), deleteDialog: $("deleteJourneyDialog"), deleteName: $("deleteJourneyName"), cancelDelete: $("cancelDelete"), confirmDelete: $("confirmDelete"), deleteStatus: $("deleteJourneyStatus") };
let currentUser = null, journeyPendingDeletion = null;
const isScopelyUser = user => Boolean(user?.email && user.email.toLowerCase().endsWith("@scopely.com"));
const isHubAdmin = () => currentUser?.email?.toLowerCase() === hubAdminEmail.toLowerCase();
const canManageJourney = journey => isHubAdmin() || journey.ownerUid === currentUser?.uid || journey.ownerEmail?.toLowerCase() === currentUser?.email?.toLowerCase();
const escapeHtml = value => String(value ?? "").replace(/[&<>'"]/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char]);
const initials = (name = "Journey") => name.trim().split(/\s+/).slice(0, 2).map(part => part[0]?.toUpperCase() || "").join("") || "J";
const journeyLink = id => id === "9dc23f8e-8b42-4a75-b7d2-91b3f1df46ad" ? "index.html" : `index.html?workspace=${encodeURIComponent(id)}`;
const displayStatus = status => ({ Production: "Active", "In Progress": "Active" }[status] || status || "Active");
function setLoginMessage(message, error = false) { els.loginMessage.textContent = message; els.loginMessage.classList.toggle("error", error); }
function showGate(message = "") { els.loginGate.hidden = false; els.hubShell.hidden = true; setLoginMessage(message); }
function showHub(user) { const firstName = (user.displayName || "there").trim().split(/\s+/)[0]; els.loginGate.hidden = true; els.hubShell.hidden = false; els.userName.textContent = user.displayName || "Scopely user"; els.userEmail.textContent = user.email || ""; els.welcomeTitle.textContent = `Welcome back, ${firstName} 👋`; if (user.photoURL) { els.userAvatar.src = user.photoURL; els.userAvatar.hidden = false; } else els.userAvatar.hidden = true; }
function formatDate(value) { if (!value) return "Start date not set"; const date = new Date(`${value}T00:00:00`); return Number.isNaN(date.getTime()) ? "Start date not set" : `Started ${new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" }).format(date)}`; }
function localDay(value) { const date = new Date(`${value || ""}T00:00:00`); return Number.isNaN(date.getTime()) ? null : date; }
function journeySummary(journey) {
  const start = localDay(journey.startDate || journey.workspaceData?.weeks?.[0]?.start), today = new Date(); today.setHours(0, 0, 0, 0);
  const weeks = journey.workspaceData?.weeks || [], totalWeeks = Math.max(1, weeks.length || 13), tasks = weeks.flatMap(week => week.actions || []), complete = tasks.filter(task => task.done).length, completedPercent = tasks.length ? Math.round(complete / tasks.length * 100) : 0, formattedStart = start ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" }).format(start) : "date not set";
  if (!start || today < start) { const days = start ? Math.round((start - today) / 86400000) : null; return { status: "Not Started", percent: 0, weekLabel: "Not Started", detail: start ? `Not Started · Starts ${formattedStart} (${days} day${days === 1 ? "" : "s"})` : "Not Started · Start date not set" }; }
  const elapsedDays = Math.round((today - start) / 86400000), allComplete = tasks.length > 0 && complete === tasks.length;
  if (allComplete || elapsedDays >= 90) return { status: "Completed", percent: 100, weekLabel: "Completed", detail: `Completed · Started ${formattedStart}` };
  const week = Math.min(Math.floor(elapsedDays / 7) + 1, totalWeeks);
  return { status: "Active", percent: completedPercent, weekLabel: `Week ${week} of ${totalWeeks}`, detail: `Week ${week} of ${totalWeeks} · ${completedPercent}% complete · Started ${formattedStart}` };
}
function openDeleteDialog(journey, name) { journeyPendingDeletion = journey; els.deleteName.textContent = name; els.deleteStatus.textContent = ""; els.confirmDelete.disabled = false; els.deleteDialog.showModal(); }
function renderRoleLibrary() {
  const search = els.roleSearch.value.trim().toLowerCase();
  const filtered = roles.filter(role => `${role.name} ${role.category} ${role.description}`.toLowerCase().includes(search));
  els.roleCount.textContent = `${filtered.length} of ${roles.length} roles`;
  els.roleLibraryGrid.innerHTML = filtered.map(role => `<article class="official-role-card ${role.status === "Ready" ? "ready" : "coming-soon"}"><div class="official-role-top"><span class="role-initials">${escapeHtml(initials(role.name))}</span><span class="role-status ${role.status === "Ready" ? "ready-status" : ""}">${role.status}</span></div><p class="role-category">${escapeHtml(role.category)}</p><h3>${escapeHtml(role.name)}</h3><p>${escapeHtml(role.description)}</p>${role.status === "Ready" ? `<a class="template-use" href="index.html?template=${encodeURIComponent(role.id)}">View template</a>` : ""}</article>`).join("") || '<p class="state-card">No roles match your search.</p>';
}
function renderJourneys(journeys) { els.journeyGrid.innerHTML = ""; els.journeyCount.textContent = String(journeys.length); if (els.viewAllJourneys) els.viewAllJourneys.hidden = journeys.length <= 2; if (!journeys.length) { els.journeyState.innerHTML = `<strong>No onboarding journeys yet.</strong><span>Choose a role template and create the first journey for your team.</span><a class="button primary" href="new-journey.html">+ New Journey</a>`; els.journeyState.hidden = false; els.journeyGrid.hidden = true; return; } journeys.forEach(journey => { const card = document.createElement("article"), name = journey.employeeName || `${journey.roleTitle || "Journey"} draft`, source = journey.managerTemplateId ? `managerTemplate=${encodeURIComponent(journey.managerTemplateId)}` : `template=${encodeURIComponent(journey.templateId)}`, href = journey.draft ? `assign.html?${source}&draft=${encodeURIComponent(journey.id)}` : journeyLink(journey.id), summary = journey.draft ? { status: "Draft", percent: 0, weekLabel: "Setup not completed", detail: "Setup not completed" } : journeySummary(journey); card.className = "journey-card"; card.dataset.progress = String(summary.percent); card.dataset.weekLabel = summary.weekLabel; card.innerHTML = `<a class="journey-open" href="${href}"><div class="journey-top"><span class="person-initials">${initials(journey.employeeName || journey.roleTitle)}</span><span class="active-badge">${escapeHtml(summary.status)}</span></div><div class="journey-card-copy"><h3>${escapeHtml(name)}</h3><p class="journey-role">${escapeHtml(journey.roleTitle || journey.template || "Onboarding journey")}</p><p class="journey-detail">${escapeHtml(summary.detail)}</p></div><span class="open-label">${journey.draft ? "Continue Setup →" : "Open Journey →"}</span></a>${canManageJourney(journey) ? '<button class="journey-more" type="button" aria-label="Remove Journey">•••</button>' : ""}`; card.querySelector(".journey-more")?.addEventListener("click", () => openDeleteDialog(journey, name)); els.journeyGrid.appendChild(card); }); els.journeyState.hidden = true; els.journeyGrid.hidden = false; }
async function loadJourneys() { els.journeyState.textContent = "Loading journeys…"; try { let snapshot; try { snapshot = await getDocs(query(collection(db, "workspaces"), orderBy("updatedAt", "desc"))); } catch { snapshot = await getDocs(collection(db, "workspaces")); } renderJourneys(snapshot.docs.map(item => ({ id: item.id, ...item.data() }))); } catch (error) { console.error(error); els.journeyCount.textContent = "0"; els.journeyState.textContent = "Journeys could not be loaded. Please refresh and try again."; els.journeyState.classList.add("error"); } }
async function handleSignIn() { els.signInButton.disabled = true; setLoginMessage("Opening Google sign-in…"); try { await setPersistence(auth, browserLocalPersistence); const result = await signInWithPopup(auth, provider); if (!isScopelyUser(result.user)) { await signOut(auth); throw new Error("Please use your Scopely Google account."); } } catch (error) { if (["auth/popup-blocked", "auth/operation-not-supported-in-this-environment"].includes(error?.code)) { setLoginMessage("Continuing to Google sign-in…"); await signInWithRedirect(auth, provider); return; } setLoginMessage(error?.message || "Sign-in failed.", true); } finally { els.signInButton.disabled = false; } }
els.roleSearch.addEventListener("input", renderRoleLibrary); els.signInButton.addEventListener("click", handleSignIn); els.signOutButton.addEventListener("click", () => signOut(auth)); els.cancelDelete.addEventListener("click", () => els.deleteDialog.close());
els.confirmDelete.addEventListener("click", async () => { if (!journeyPendingDeletion || !canManageJourney(journeyPendingDeletion)) return; els.confirmDelete.disabled = true; els.deleteStatus.textContent = "Deleting Journey…"; try { await deleteDoc(doc(db, "workspaces", journeyPendingDeletion.id)); els.deleteDialog.close(); journeyPendingDeletion = null; await loadJourneys(); } catch (error) { els.deleteStatus.textContent = error?.code === "permission-denied" ? "Deletion is blocked by Firestore rules." : "Journey could not be deleted."; els.confirmDelete.disabled = false; } });
function decorateJourneyProgress() { document.querySelectorAll(".journey-card").forEach(card => { if (card.dataset.progressReady) return; const percent = Math.max(0, Math.min(100, Number(card.dataset.progress || 0))), week = card.dataset.weekLabel || "Not Started", block = document.createElement("div"); card.dataset.progressReady = "true"; block.className = "journey-progress"; block.innerHTML = `<div class="journey-progress-label"><span>${escapeHtml(week)}</span><strong>${percent}%</strong></div><div class="journey-track"><span style="width:${percent}%"></span></div>`; card.querySelector(".open-label")?.before(block); }); }
new MutationObserver(decorateJourneyProgress).observe(els.journeyGrid, { childList: true, subtree: true });
onAuthStateChanged(auth, async user => { if (!user) { currentUser = null; return showGate(); } if (!isScopelyUser(user)) { await signOut(auth); return showGate("Please use your Scopely Google account."); } currentUser = user; showHub(user); renderRoleLibrary(); await loadJourneys(); });
