import { initializeApp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import { browserLocalPersistence, getAuth, GoogleAuthProvider, onAuthStateChanged, setPersistence, signInWithPopup, signOut } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import { collection, deleteDoc, doc, getDocs, getFirestore, orderBy, query, where } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import { firebaseConfig, hubAdminEmail } from "./firebase-config.js";

const app = initializeApp(firebaseConfig, "lgp-onboarding-hub"), auth = getAuth(app), db = getFirestore(app), provider = new GoogleAuthProvider();
provider.setCustomParameters({ hd: "scopely.com" });
const $ = id => document.getElementById(id);
const els = { loginGate: $("loginGate"), hubShell: $("hubShell"), signInButton: $("signInButton"), signOutButton: $("signOutButton"), loginMessage: $("loginMessage"), userName: $("userName"), userEmail: $("userEmail"), userAvatar: $("userAvatar"), journeyGrid: $("journeyGrid"), journeyState: $("journeyState"), journeyCount: $("journeyCount"), myTemplateGrid: $("myTemplateGrid"), myTemplateState: $("myTemplateState"), myTemplateCount: $("myTemplateCount"), startJourneyButton: $("startJourneyButton"), deleteDialog: $("deleteJourneyDialog"), deleteName: $("deleteJourneyName"), cancelDelete: $("cancelDelete"), confirmDelete: $("confirmDelete"), deleteStatus: $("deleteJourneyStatus") };
let currentUser = null, journeyPendingDeletion = null;
const isScopelyUser = user => Boolean(user?.email && user.email.toLowerCase().endsWith("@scopely.com"));
const isHubAdmin = () => currentUser?.email?.toLowerCase() === hubAdminEmail.toLowerCase();
const canManageJourney = journey => isHubAdmin() || journey.ownerUid === currentUser?.uid || journey.ownerEmail?.toLowerCase() === currentUser?.email?.toLowerCase();
const escapeHtml = value => String(value ?? "").replace(/[&<>'"]/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char]);
const initials = (name = "Journey") => name.trim().split(/\s+/).slice(0, 2).map(part => part[0]?.toUpperCase() || "").join("") || "J";
const journeyLink = id => id === "9dc23f8e-8b42-4a75-b7d2-91b3f1df46ad" ? "index.html" : `index.html?workspace=${encodeURIComponent(id)}`;
function setLoginMessage(message, error = false) { els.loginMessage.textContent = message; els.loginMessage.classList.toggle("error", error); }
function showGate(message = "") { els.loginGate.hidden = false; els.hubShell.hidden = true; setLoginMessage(message); }
function showHub(user) { els.loginGate.hidden = true; els.hubShell.hidden = false; els.userName.textContent = user.displayName || "Scopely user"; els.userEmail.textContent = user.email || ""; if (user.photoURL) { els.userAvatar.src = user.photoURL; els.userAvatar.hidden = false; } else els.userAvatar.hidden = true; }
function formatDate(value) { if (!value) return "Start date not set"; const date = new Date(`${value}T00:00:00`); return Number.isNaN(date.getTime()) ? "Start date not set" : `Started ${new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" }).format(date)}`; }
function openDeleteDialog(journey, name) { journeyPendingDeletion = journey; els.deleteName.textContent = name; els.deleteStatus.textContent = ""; els.confirmDelete.disabled = false; els.deleteDialog.showModal(); }
function renderJourneys(journeys) { els.journeyGrid.innerHTML = ""; els.journeyCount.textContent = String(journeys.length); if (!journeys.length) { els.journeyState.textContent = "No onboarding journeys are available yet."; els.journeyState.hidden = false; els.journeyGrid.hidden = true; return; } journeys.forEach(journey => { const card = document.createElement("article"), name = journey.employeeName || `${journey.roleTitle || "Journey"} draft`, source = journey.managerTemplateId ? `managerTemplate=${encodeURIComponent(journey.managerTemplateId)}` : `template=${encodeURIComponent(journey.templateId)}`, href = journey.draft ? `assign.html?${source}&draft=${encodeURIComponent(journey.id)}` : journeyLink(journey.id), detail = journey.draft ? `${formatDate(journey.startDate)} · Setup not submitted` : formatDate(journey.startDate); card.className = "journey-card"; card.innerHTML = `<a class="journey-open" href="${href}"><div class="journey-top"><span class="person-initials">${initials(journey.employeeName || journey.roleTitle)}</span><span class="active-badge">${escapeHtml(journey.status || "Active")}</span></div><h3>${escapeHtml(name)}</h3><p class="journey-role">${escapeHtml(journey.roleTitle || journey.template || "Onboarding journey")}</p><div class="journey-meta"><span>${escapeHtml(detail)}</span><span class="open-label">${journey.draft ? "Continue draft →" : "Open Journey →"}</span></div></a>${canManageJourney(journey) ? '<button class="journey-delete" type="button" aria-label="Delete Journey">×</button>' : ""}`; card.querySelector(".journey-delete")?.addEventListener("click", () => openDeleteDialog(journey, name)); els.journeyGrid.appendChild(card); }); els.journeyState.hidden = true; els.journeyGrid.hidden = false; }
function renderMyTemplates(templates) { els.myTemplateGrid.innerHTML = ""; els.myTemplateCount.textContent = String(templates.length); if (!templates.length) { els.myTemplateState.textContent = "No personal templates yet. Open an official template, review it, then select Edit Template to create your own copy."; els.myTemplateState.hidden = false; els.myTemplateGrid.hidden = true; return; } templates.forEach(template => { const card = document.createElement("article"), updated = template.updatedAt?.toDate?.() ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" }).format(template.updatedAt.toDate()) : "Recently"; card.className = "template-card ready"; card.innerHTML = `<div class="template-icon">${escapeHtml(initials(template.name || "My"))}</div><div><span class="status ready-status">${escapeHtml(template.status === "ready" ? "Ready" : "Draft")}</span><h3>${escapeHtml(template.name)}</h3><p>${escapeHtml(template.teamName ? `${template.sourceRole || "Custom template"} · ${template.teamName}` : template.sourceRole || "Custom template")}</p><small class="template-detail">Updated ${escapeHtml(updated)}</small><a class="template-use" href="index.html?managerTemplate=${encodeURIComponent(template.id)}">Open template</a></div>`; els.myTemplateGrid.appendChild(card); }); els.myTemplateState.hidden = true; els.myTemplateGrid.hidden = false; }
async function loadJourneys() { els.journeyState.textContent = "Loading journeys…"; try { let snapshot; try { snapshot = await getDocs(query(collection(db, "workspaces"), orderBy("startDate", "desc"))); } catch { snapshot = await getDocs(collection(db, "workspaces")); } renderJourneys(snapshot.docs.map(item => ({ id: item.id, ...item.data() })).sort((a, b) => String(b.startDate || "").localeCompare(String(a.startDate || "")))); } catch (error) { console.error(error); els.journeyCount.textContent = "0"; els.journeyState.textContent = "Journeys could not be loaded. Please refresh and try again."; els.journeyState.classList.add("error"); } }
async function loadMyTemplates() { els.myTemplateState.textContent = "Loading your templates…"; try { let snapshot; try { snapshot = await getDocs(query(collection(db, "managerTemplates"), where("ownerUserId", "==", currentUser.uid), orderBy("updatedAt", "desc"))); } catch { snapshot = await getDocs(query(collection(db, "managerTemplates"), where("ownerUserId", "==", currentUser.uid))); } renderMyTemplates(snapshot.docs.map(item => ({ id: item.id, ...item.data() }))); } catch (error) { console.error(error); els.myTemplateCount.textContent = "0"; els.myTemplateState.textContent = error?.code === "permission-denied" ? "Publish the updated Firestore rules to enable My Templates." : "Your templates could not be loaded."; els.myTemplateState.classList.add("error"); } }
async function handleSignIn() { els.signInButton.disabled = true; setLoginMessage("Opening Google sign-in…"); try { await setPersistence(auth, browserLocalPersistence); const result = await signInWithPopup(auth, provider); if (!isScopelyUser(result.user)) { await signOut(auth); throw new Error("Please use your Scopely Google account."); } } catch (error) { setLoginMessage(error?.message || "Sign-in failed.", true); } finally { els.signInButton.disabled = false; } }
els.signInButton.addEventListener("click", handleSignIn); els.signOutButton.addEventListener("click", () => signOut(auth)); els.startJourneyButton.addEventListener("click", () => $("templatesTitle")?.scrollIntoView({ behavior: "smooth", block: "start" })); els.cancelDelete.addEventListener("click", () => els.deleteDialog.close());
els.confirmDelete.addEventListener("click", async () => { if (!journeyPendingDeletion || !canManageJourney(journeyPendingDeletion)) return; els.confirmDelete.disabled = true; els.deleteStatus.textContent = "Deleting Journey…"; try { await deleteDoc(doc(db, "workspaces", journeyPendingDeletion.id)); els.deleteDialog.close(); journeyPendingDeletion = null; await loadJourneys(); } catch (error) { els.deleteStatus.textContent = error?.code === "permission-denied" ? "Deletion is blocked by Firestore rules." : "Journey could not be deleted."; els.confirmDelete.disabled = false; } });
onAuthStateChanged(auth, async user => { if (!user) { currentUser = null; return showGate(); } if (!isScopelyUser(user)) { await signOut(auth); return showGate("Please use your Scopely Google account."); } currentUser = user; showHub(user); await Promise.all([loadJourneys(), loadMyTemplates()]); });
